# Missing Data

In [5]:
import numpy as np
import pandas as pd

What does "missing data" mean? What is a missing value? It depends on the origin of the data and the context it was generated. For example, for a survey, a _`Salary`_ field with an empty value, or a number 0, or an invalid value (a string for example) can be considered "missing data". These concepts are related to the values that Python will consider "Falsy":

In [ ]:
falsy_values = (0, False, None, '', [], {})

In [12]:
3 + None

nan

For Python, all the values above are considered "falsy":

In [ ]:
any(falsy_values)

Numpy has a special "nullable" value for numbers which is `np.nan`. It's _NaN_: "Not a number"

In [6]:
np.nan

nan

The `np.nan` value is kind of a virus. Everything that it touches becomes `np.nan`:

In [7]:
3 + np.nan

nan

In [8]:
a = np.array([1, 2, 3, np.nan, np.nan, 4])

In [9]:
a.sum()

nan

In [10]:
a.mean()

nan

This is better than regular `None` values, which in the previous examples would have raised an exception:

In [ ]:
3 + None

For a numeric array, the `None` value is replaced by `np.nan`:

In [13]:
a = np.array([1, 2, 3, np.nan, None, 4], dtype='float')

In [14]:
a

array([ 1.,  2.,  3., nan, nan,  4.])

As we said, `np.nan` is like a virus. If you have any `nan` value in an array and you try to perform an operation on it, you'll get unexpected results:

In [15]:
a = np.array([1, 2, 3, np.nan, np.nan, 4])

In [16]:
a.mean()

nan

In [17]:
a.sum()

nan

Numpy also supports an "Infinite" type:

In [18]:
np.inf

inf

Which also behaves as a virus:

In [19]:
3 + np.inf

inf

In [20]:
np.inf / 3

inf

In [21]:
np.inf / np.inf

nan

In [22]:
b = np.array([1, 2, 3, np.inf, np.nan, 4], dtype=np.float)

C:\Users\cm computers\AppData\Local\Temp\ipykernel_3404\2748397628.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  b = np.array([1, 2, 3, np.inf, np.nan, 4], dtype=np.float)


In [23]:
b.sum()

nan

![separator1](https://i.imgur.com/ZUWYTii.png)

### Checking for `nan` or `inf`

There are two functions: `np.isnan` and `np.isinf` that will perform the desired checks:

In [24]:
np.isnan(np.nan)

True

In [25]:
np.isinf(np.inf)

True

And the joint operation can be performed with `np.isfinite`.

In [26]:
np.isfinite(np.nan), np.isfinite(np.inf)

(False, False)

`np.isnan` and `np.isinf` also take arrays as inputs, and return boolean arrays as results:

In [27]:
np.isnan(np.array([1, 2, 3, np.nan, np.inf, 4]))

array([False, False, False,  True, False, False])

In [28]:
np.isinf(np.array([1, 2, 3, np.nan, np.inf, 4]))

array([False, False, False, False,  True, False])

In [29]:
np.isfinite(np.array([1, 2, 3, np.nan, np.inf, 4]))

array([ True,  True,  True, False, False,  True])

_Note: It's not so common to find infinite values. From now on, we'll keep working with only `np.nan`_

![separator1](https://i.imgur.com/ZUWYTii.png)

### Filtering them out

Whenever you're trying to perform an operation with a Numpy array and you know there might be missing values, you'll need to filter them out before proceeding, to avoid `nan` propagation. We'll use a combination of the previous `np.isnan` + boolean arrays for this purpose:

In [31]:
a = np.array([1, 2, 3, np.nan, np.nan, 4])
a

array([ 1.,  2.,  3., nan, nan,  4.])

In [33]:
~np.isnan(a)

array([ True,  True,  True, False, False,  True])

In [34]:
a[~np.isnan(a)]

array([1., 2., 3., 4.])

Which is equivalent to:

In [35]:
a[np.isfinite(a)]

array([1., 2., 3., 4.])

And with that result, all the operation can be now performed:

In [36]:
a[np.isfinite(a)].sum()

10.0

In [37]:
a[np.isfinite(a)].mean()

2.5

![separator2](https://i.imgur.com/4gX5WFr.png)